Test schema params
safety-analytics-mapping/pysqldb3 pull request #24
Opened 2022-10-28 14:10 UTC by EricRenart

pgsql tests in test_query_renames_table.py passing, including test_query_renames_table_logging_not_temp
all SQL tests passing on local machine except test_query_renames_table_multiple (14/15 total in file)

2022-10-28 20:31 UTC, EricRenart commented
15/15 tests passing in test_query_renames_table

2022-10-31 13:35 UTC, shostetter requested changes
You shouldnt push the config files (easy thing to forget). Once they are removed we can merge this, all tests passed for me

2022-10-31 13:50 UTC, shostetter commented
Great, can you add a sample_db_config.cfg and sample_config.cfg that has the parameters without the values so anyone starting can know what is required

2022-10-31 14:09 UTC, shostetter approved these changes

2022-10-31 14:09 UTC, merged